# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d17d192734c14ccb2507dd0c7eb791cf813306968675c91491c96600fc7b66260e5d09f4d3c74ca2db23aec9f8df5c9848c5619f0e7cb18a7e60fdb45c996f2c

test:
  secret_key_base: ab7d22b3704d38992afe592ec483c2db013e9364e61ed2d5f853628ccf284b74c145047695ba03765b584546e4589cd6eeee56b5f25070ed670cf5c58df3f8ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
